
services:
  # Servicio 1: Nuestra aplicación Flask
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    command: python app/app.py
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      db:
        condition: service_healthy

  # Servicio 2: Servidor PostgreSQL
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Servicio 3: Adminer (Gestor visual de DB)
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"

  
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # Puerto para la API de la app
      - "9001:9001" # Puerto para la Consola Web (El "Drive")
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL}
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  minio_data: